/****** Object:  Index [NonClusteredIndex-20161229-154827]    Script Date: 29.12.2016 15:53:00 ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20161229-154827] ON [dbo].[Event]
(
	[StartDateTime] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

GO

/****** Object:  Index [NonClusteredIndex-20161229-110836]    Script Date: 29.12.2016 15:53:16 ******/
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20161229-110836] ON [dbo].[DiscussionItem]
(
	[DateTime] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

GO

CREATE NONCLUSTERED INDEX [NonClusteredIndex-20161229-161425] ON [dbo].[EventParticipant]
(
	[EventLoginStatus] ASC
)
INCLUDE ( 	[Id_User],
	[Id_Event]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)



