// <auto-generated />
namespace _3F.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class EventInvitation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EventInvitation));
        
        string IMigrationMetadata.Id
        {
            get { return "201605092102363_EventInvitation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
