// <auto-generated />
namespace _3F.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class UnifyPostsAndFileDescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UnifyPostsAndFileDescription));
        
        string IMigrationMetadata.Id
        {
            get { return "201709201333580_UnifyPostsAndFileDescription"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
